train_config:
  num_days: 3
  epoch_every_num_days: 1
  num_collection_steps: 3
  num_envs: 1
  num_workers: 1
  allow_to_act_in_terminal_state_once: false
  env_name: 'MiniHack-MemoryTest-Combined-v0'
  observation_keys: ['glyphs', 'blstats']
  agent_type: 'muzero'
  replay_buffer:
    type: uniform_over_good_and_bad
    cluster_buffer:
      type: max_age
      max_buffer_size: 50000
      max_age: 10
    good_total_reward_threshold: 0.5
agent_config:
  use_priorities: false
  update_next_trajectory_memory: true
  lr: 0.001
  discount_factor: 0.999
  num_train_steps: 1
  num_train_unroll_steps: 2
  reanalyze_batch_size: 1
  num_mcts_simulations: 2
  reward_values: [-0.01, 0.0, -1.0, 1.0]
  model_config:
    num_chance_outcomes: 16
    context_dependent_state_encoder: false
    normalize_state: true
    state_encoder_config:
      num_perceiver_blocks: 1
      num_perceiver_self_attention_subblocks: 1
      num_memory_units: 3
      memory_dim: 16
      glyph_embedding_dim: 16
      transformer_fc_inner_dim: 16
      use_fixed_positional_embeddings: false
      use_bl_stats: true
      num_bl_stats_blocks: 1
      bl_stats_log_transform: true
      glyph_crop_size: [5, 5]
    scalar_predictor_config:
      transformer_num_blocks: 1
      transformer_num_heads: 1
      transformer_fc_inner_dim: 16
    action_outcome_predictor_config:
      transformer_num_blocks: 1
      transformer_num_heads: 1
      transformer_fc_inner_dim: 16
    dynamics_transformer_config:
      num_blocks: 1
      num_heads: 1
      fc_inner_dim: 16
      use_gating: true
    memory_aggregator_config:
      num_blocks: 1
      num_heads: 1
      fc_inner_dim: 16
      use_gating: true
