train_config:
  num_days: 5
  epoch_every_num_days: 1
  num_collection_steps: 3
  num_envs: 1
  num_workers: 1
  allow_to_act_in_terminal_state_once: false
  env_name: 'MiniHack-MazeWalk-11x11-v0'
  observation_keys: ['glyphs', 'blstats']
  keep_bl_stats: ['hitpoints']
  agent_type: 'muzero'
  replay_buffer:
    type: uniform_over_good_and_bad
    cluster_buffer:
      type: max_age
      max_buffer_size: 50000
      max_age: 1
    good_total_reward_threshold: 0.5
    distribution_power: 0.5
agent_config:
  use_priorities: false
  use_importance_weights: true
  update_next_trajectory_memory: true
  lr: 0.000075
  use_adaptive_lr: true
  no_weight_decay_layers: ['bias']
  discount_factor: 0.999
  num_train_steps: 1
  num_train_unroll_steps: 2
  warmup_days: 0
  reanalyze_batch_size: 1
  num_mcts_simulations: 2
  mcts_reward_ensemble_size: 3
  exploration_optimism: 1.0
  model_config:
    num_chance_outcomes: 16
    context_dependent_state_encoder: true
    normalize_state: false
    state_encoder_config:
      num_perceiver_blocks: 1
      num_perceiver_self_attention_subblocks: 1
      num_memory_units: 3
      memory_dim: 16
      transformer_fc_inner_dim: 16
      use_fixed_positional_embeddings: false
      use_bl_stats: true
      num_bl_stats_blocks: 1
      glyph_crop_size: [5, 5]
    scalar_predictor_config:
      transformer_num_blocks: 1
      transformer_num_heads: 1
      transformer_fc_inner_dim: 16
    action_outcome_predictor_config:
      transformer_num_blocks: 1
      transformer_num_heads: 1
      transformer_fc_inner_dim: 16
    dynamics_transformer_config:
      num_blocks: 1
      num_heads: 1
      fc_inner_dim: 16
      gate: gru
    memory_aggregator_config:
      num_blocks: 1
      num_heads: 1
      fc_inner_dim: 16
      gate: 'highway'
